export const lots = [
    {
        key: 0,
        lot: 1,
        type: false,
        model: '',
        color: '',
        board: '',
        owner: '',
        hour: '',
        port: '',
        payment: '',
        isApplication: false,
    },
    {
        key: 1,
        lot: 2,
        type: false,
        model: '',
        color: '',
        board: '',
        owner: '',
        hour: '',
        port: '',
        payment: '',
        isApplication: false,
    },
    {
        key: 2,
        lot: 3,
        type: false,
        model: '',
        color: '',
        board: '',
        owner: '',
        hour: '',
        port: '',
        payment: '',
        isApplication: false,
    },
    {
        key: 3,
        lot: 4,
        type: true,
        model: '',
        color: '',
        board: '',
        owner: '',
        hour: '',
        port: '',
        payment: '',
        isApplication: false,
    },
    {
        key: 4,
        lot: 5,
        type: false,
        model: '',
        color: '',
        board: '',
        owner: '',
        hour: '',
        port: '',
        payment: '',
        isApplication: false,
    },
    {
        key: 5,
        lot: 6,
        type: false,
        model: '',
        color: '',
        board: '',
        owner: '',
        hour: '',
        port: '',
        payment: '',
        isApplication: false,
    },
    {
        key: 6,
        lot: 7,
        type: true,
        model: '',
        color: '',
        board: '',
        owner: '',
        hour: '',
        port: '',
        payment: '',
        isApplication: false,
    },
];
